### ISSUE TITLE
Utils.createHostFunction and casted delegates

### ISSUE THREAD

**Issue by jhlllnd** [fholm/IronJS#10]
Hi,

first, thank you for this awesome code :)

I have found an annoying limitation. If the delegate at createHostFunction is casted to a Delegate it throws a NullReferenceException.

Utils.createHostFunction(env, (Delegate)new Action(this.test));

A quick fix from this:
    ArgTypes = FSKit.Reflection.getDelegateArgTypesT<'a>
    ReturnType = FSKit.Reflection.getDelegateReturnTypeT<'a>
to this:
    ArgTypes = FSKit.Reflection.getDelegateArgTypes(delegate'.GetType())
    ReturnType = FSKit.Reflection.getDelegateReturnType(delegate'.GetType())
doesn't help.

I am trying to bind dynamically methods of an object to js functions with Delegate.CreateDelegate like so:
    List<Type> args = new List<Type>(method.GetParameters().Select(p => p.ParameterType));
    Type delegateType;
    if(method.ReturnType == typeof(void))
    {
        delegateType = Expression.GetActionType(args.ToArray());
    }
    else
    {
        args.Add(method.ReturnType);
        delegateType = Expression.GetFuncType(args.ToArray());
    }

```
var del = Delegate.CreateDelegate(delegateType, target, method);

Utils.createHostFunction(env, del);
```

**Comment by fholm** [comment]
Thanks for reporting this issue, it should be fixxed in commit [a77557f](https://github.com/fholm/IronJS/commit/a77557ffe135e68df8cc310ca0ec28874c28ef2b) by adding a function in IronJS.Native.Utils called createHostFunctionDynamic which takes a System.Delegate as last argument and uses reflection to resolve all types.

**Comment by fholm** [comment]
Also, here's an example of it would look when used:

```
//Example of using createHostFunctionDynamic
let print = new Action<string>(System.Console.WriteLine) :> Delegate
let printFunc = IronJS.Native.Utils.createHostFunctionDynamic ctx.Environment print
ctx.PutGlobal("print", printFunc)
ctx.Execute("print('lol')");
```

**Comment by jhlllnd** [comment]
Many thanks for the very quick fix!

But I think you forgot to upload the latest FSKit changes :)

**Comment by fholm** [comment]
Pushed latest FSKit now :)

**Comment by fholm** [comment]
Also note that I changed the fix around a bit, so just call createHostFunction like you use to and it will check if the argument is "System.Delegate" and invoke createHostFunctionDynamic by itself.
