### ISSUE TITLE
CLR4.sln does not compile

### ISSUE THREAD

**Issue by axefrog** [fholm/IronJS#11]
Hi, I just followed the instructions in README.markdown, then loaded CLR4.sln and got a compile error. The output window has this:

```
C:\Users\Dell\My Dropbox\Work\Sandbox\Third Party\IronJS\Src\IronJS\Native.Utils.fs(39,20): error FS0039: The value, constructor, namespace or type 'isSameTypeT' is not defined
```

The error window has this:

```
Error   1   Assembly reference 'C:\xxxxxxxxxxx\IronJS\Src\IronJS\bin\Debug\IronJS.dll' was not found or is invalid  FSC 1   1   REPL
```

**Comment by fholm** [comment]
If you checkout the master FSKit branch it should compile, I've missed to update the readme file. "git checkout master" in Src/FSKit and you should be fine.

**Comment by axefrog** [comment]
Ok thanks I'll try that. Do you have a roadmap or some way to quickly see what the engine still needs before it's "feature complete"?

**Comment by fholm** [comment]
No "official" roadmap, but here are the three main things missing currently: 1) Full RegExp support in String.prototype and implementation of RegExp.prototype.exec, 2) The entire Date object needs to be implemented 3) A few of the Array.prototype functions currently only work on Array objects (and not on normal Objects which they also should). After that it is "feature complete" with the ECMA3 standard. But as in all software there might be bugs here and there.

I expect to have the three missing features complete by the end of March.

**Comment by axefrog** [comment]
Ok thanks cool, I'll keep watching!
