### ISSUE TITLE
A conditional expression containing an assignment as its last element fails to compile.

### ISSUE THREAD

**Issue by otac0n** [fholm/IronJS#26]
This case fails:
`true ? foo="a" : foo="b";
print(foo);`

This case passes:
`true ? (foo="a") : (foo="b");
print(foo);`

**Comment by otac0n** [comment]
These expressions should be roughly equivalent:
`true ? foo="a" : foo="b";`
and
`foo = true ? "a" : "b";`

However, my attempts to resolve this issue have been thwarted by the fact that swaping the binding power of the conditional causes this interpretation:
`true ? (foo="a") : (foo="b");`  and `(foo = true) ? "a" : "b";`

Whereas using the binding power of Assignment to read the expression after the colon cause this interpretation:
`(true ? foo="a" : foo) = "b";`  and `foo = (true ? "a" : "b");`

**Comment by fholm** [comment]
I'll look into it asap.

**Comment by fholm** [comment]
Fixed in commit [0220cabadb919](https://github.com/fholm/IronJS/commit/0220cabadb919bcc16389d145e9d97b4cb12ec9a)
