### ISSUE TITLE
IronJS needs a .nuspec package definition.

### ISSUE THREAD

**Issue by otac0n** [fholm/IronJS#29]
NuGet, the defacto standard package management app for .NET, is a great place to distribute IronJS.

In order to get IronJS onto NuGet's official package source, we need to package up the IronJS binaries according to the ".nuspec" format.

**Comment by fholm** [comment]
Awesome idea, got my full support.

**Comment by andersarpi** [comment]
I think this is a great idea. I think NuGet is an outstanding addition to VS and getting IronJS into it will probably get some people to check it out that aren't quite curious enough for a clone.

A question regarding NuGet standards though, should we really just bundle the binaries and not the entire source code?

**Comment by fholm** [comment]
@holmstrom about the NuGet standards, whatever is the standard we will do (im not sure if the source is included also).

**Comment by otac0n** [comment]
The standard is to release a binary-only package `Foo` and a source code package, separately `Foo.Source`.

**Comment by fholm** [comment]
@otac0n: Then I think that's the best way to do it.

**Comment by otac0n** [comment]
Fixed in commit [09e0ea8934808](https://github.com/fholm/IronJS/commit/09e0ea8934808ae8a99e84d9a475d56620027ce1)
