### ISSUE TITLE
FunctionObject.apply() throws TargetParameterCountException for variadic functions.

### ISSUE THREAD

**Issue by otac0n** [fholm/IronJS#31]
This affects the V8 Raytrace test.

Here is the minimum repro case:

```
var foo = function(a, b, c, d, e) {
    print(a + ", " + b + ", " + c + ", " + d + ", " + e);
};

var callFoo = function () {
    foo.apply(foo, arguments);
};

foo("1", "2", "3", "4", "5");
callFoo("A", "B", "C", "D", "E");
```

**Comment by otac0n** [comment]
This is happening because the Delagate returned for variadic functions is (essentially) `Func<BoxedValue[], BoxedValue>` instead of `Func<BoxedValue, BoxedValue, BoxedValue, ..., BoxedValue>`. which is then called with `args`, instead of `new object[] { args }`

**Comment by fholm** [comment]
Awesome work!
