### ISSUE TITLE
A bug.

### ISSUE THREAD

**Issue by treenewlyn** [fholm/IronJS#46]
JS Code:

show(Add(123,4));

C# code:
        static void Print(object value)
        {
            MessageBox.Show(value.ToString());
        }
        static double Add(double x, double y)
        {
            return x + y;
        }

And..... I changed the source with this:

```
    [Serializable]
    public class TestClass : IronJS.Hosting.CSharp.Context
    {
        private static readonly Type UtilsType = typeof(IronJS.Native.Utils);
        private static readonly System.Reflection.MethodInfo CreateFunctionMethod = UtilsType.GetMethod("CreateFunction", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static);
        private delegate FunctionObject CreateFunctionHandler<T>(IronJS.Environment env, int? length, T @delegate);

        public void SetFunction<T>(string name, T @delegate)
        {
            var d = Delegate.CreateDelegate(typeof(CreateFunctionHandler<T>), CreateFunctionMethod.MakeGenericMethod(typeof(T))) as CreateFunctionHandler<T>;
            var f = d(this.Environment, null, @delegate) as FunctionObject;
            this.SetGlobal(name, f);
        }
    }
```

.......

NOW.

```
 var c = new TestClass();
        context = c;
        context.CreatePrintFunction();
        context.Environment.BreakPoint = breakPoint;

        c.SetFunction("Add", new Func<double, double, double>(Add));
        c.SetFunction("show", new Action<object>(Print));
```

It's so easy.

**Comment by treenewlyn** [comment]
Oh, the bug is display Text:

MessageBox.Show("IronJS.BoxedValue");

**Comment by treenewlyn** [comment]
I must change the  Print method:
But,It's ugly.

 static void Print(object value)
        {
            if(value is BoxedValue)
            {
                value = ((BoxedValue)value).ClrBoxed;
            }
            MessageBox.Show(value.ToString());
        }

**Comment by fholm** [comment]
What is the actual bug/issue here? Not following your code/logic at all.

**Comment by treenewlyn** [comment]
In the javascript code:

ClrFunction1(ClrFuntion2());

the ClrFunction1 argument is a BoxedValue.
But i want the ClrFuntion2() Value.

**Comment by fholm** [comment]
There is currently no support for passing delegates directly into IronJS, they have to be wrapped as HostFunctionObject<T> instances, check this https://github.com/fholm/IronJS/wiki/Exposing-a-CLR-function-as-a-native-JavaScript-function post on the wiki for reference.

**Comment by treenewlyn** [comment]
The second:

## If the C# has a Method like this:

static void ClrInvokeJS(Action<string> s)
        {
            s("Hello");

##         }

Now, I register this Method to JSFunction.

## In the jsCode,I wan :

function jsfunctionTest(s)
{
    print(s);
}

## ClrInvokeJS(jsfunctionTest);

Of course, Compile failed now. But this is a good support ideas!

**Comment by treenewlyn** [comment]
Oh ,sorry. The second is support!!

```
    static void ClrInvokeJS(BoxedValue s)
    {
        if(s.IsFunction)
        {
            s.Func.Call(null, "Hello");
        }
       // s("Hello");
    }
```

**Comment by treenewlyn** [comment]
Closed.
