### ISSUE TITLE
IronJS doesn't support String.prototype.substr

### ISSUE THREAD

**Issue by asbjornu** [fholm/IronJS#49]
When executing <a href="https://github.com/mishoo/UglifyJS">UglifyJS</a> with IronJS (which I do in <a href="https://github.com/asbjornu/Uglify.NET">Uglify.NET</a>), I get the following exception:

```
IronJS.UserError: TypeError: 64
    at IronJS.Hosting.FSharp.run(Delegate compiled, T t) in D:\AUL\Dev\Misc\IronJS\Src\IronJS\Hosting.fs:line 152
    at IronJS.Hosting.CSharp.Context.Execute(String source) in D:\AUL\Dev\Misc\IronJS\Src\IronJS\Hosting.fs:line 240
    at Uglify.Uglifier.Uglify(String code) in D:\AUL\Dev\Misc\Uglify.NET\src\app\Uglify\Uglifier.cs:line 28
    at Uglify.Terminal.Terminal.Main() in D:\AUL\Dev\Misc\Uglify.NET\src\tests\Terminal\Terminal.cs:line 12
```

It occurs while executing the `parse-js.js` file, which doesn't look that special to me, but I'm unaware of IronJS' limitations, so there might be some bits in there that aren't supported. Either way, I'd love to know why it doesn't work and how and where I might be able to contribute code to make it work.

**Comment by fholm** [comment]
TypeError: N, is just a placeholder for a correct type error message. Though, the problem you're experiencing is probably because UglifyJS calls a function (in js) called require, this is something supplied by node.js, etc. which isn't built into IronJS (ironjs is a runtime, node is an application server).

**Comment by asbjornu** [comment]
As you can see in <a href="https://github.com/asbjornu/Uglify.NET/blob/master/src/app/Uglify/Uglifier.cs">`Uglifier.cs`</a>, I've defined the `require` function and <a href="https://github.com/asbjornu/Uglify.NET/blob/master/src/app/Uglify/Requirer.cs">implemented it</a>, so I don't believe that's the problem. I'm pretty sure of this since `Requirer.Require` is actually invoked and it's first when the required code is executed (line 49 in `Requirer.cs`) that I receive an exception.

If I reduce the file <a href="https://github.com/mishoo/UglifyJS/blob/master/lib/parse-js.js">`parse-js.js`</a> to nothing but a few lines of code, the execution continues, but of course fails due to missing stuff that `parse-js.js` was supposed to define. So the problem is within `parse-js.js` somewhere, but I'm unable to locate where and what.

**Comment by fholm** [comment]
Ah, sorry for my assumptions, we'll make sure to look into it asap.

**Comment by otac0n** [comment]
This is the bit of code causing issues:

```
var ASSIGNMENT = (function(a, ret, i){
        while (i < a.length) {
                ret[a[i]] = a[i].substr(0, a[i].length - 1);
                i++;
        }
        return ret;
})(
        ["+=", "-=", "/=", "*=", "%=", ">>=", "<<=", ">>>=", "|=", "^=", "&="],
        { "=": true },
        0
);
```

I'm still hunting.

**Comment by otac0n** [comment]
@asbjornu here's the fix:

```
String.prototype.substr = String.prototype.substring;
```

Here's an example:

```
if (!File.Exists("parse-js.js"))
{
    var client = new WebClient();
    client.DownloadFile("https://raw.github.com/mishoo/UglifyJS/master/lib/parse-js.js", "parse-js.js");
}

var ctx = new CSharp.Context();
ctx.Execute("var exports; String.prototype.substr = String.prototype.substring;");
ctx.ExecuteFile("parse-js.js");
Console.WriteLine("Success...");
Console.ReadKey(true);
```

**Comment by otac0n** [comment]
I'm gonna close this and open a new issue for making the error messages relevant.

**Comment by asbjornu** [comment]
Thanks! Would you say using `String.substr()` over `String.substring()` is a bug in UglifyJS or is IronJS' implementation incomplete? I'll patch this in Uglify.NET for sure, but I just wonder which upstream I should (ask to) fix.

**Comment by otac0n** [comment]
I wouldn't say that there is a bug at all, really.  Rather, this is something provided by Node that isn't part of the ES3 spec.
However, that does mean that Uglify won't run on a pure implementation so it may be worth a change request.

**Comment by asbjornu** [comment]
I've <a href="https://github.com/mishoo/UglifyJS/issues/168">asked UglifyJS to fix it</a>. I might do a fork and pull as well.

**Comment by asbjornu** [comment]
<a href="https://github.com/mishoo/UglifyJS/pull/169">Seems like</a> `String.prototype.substr` is defined in ECMA-262 (5th edition, section B.2.3), so since IronJS currently only supports a subset of ES3, it's only natural that IronJS chokes on this. It's also natural of UglifyJS to keep it in, since `substr` and `substring` <a href="https://github.com/mishoo/UglifyJS/issues/168#issuecomment-1481423">have different behavior</a>. This difference in behavior might also be the reason why just aliasing `substr` as `substring` makes Uglify.NET fail.

It seems like the most interoperable and best solution is to define `String.prototype.substr` in IronJS and implement it there. Any idea how to move forward with that?

**Comment by fholm** [comment]
Re-opening this issue so track our implementation of substr.

@asbjornu: The best way to move forward is probably for us just to implement String.prototype.substr as we start our work to implement the ES5 spec.

**Comment by asbjornu** [comment]
That would be awesome. In the meantime, how would I best go about implementing my own `substr` function in C#? I can't find any examples of how to define a prototype function, but I've tried this and it doesn't work:

```
var substr = Utils.CreateFunction<Func<int, int, CommonObject, CommonObject>>(context.Environment, 1, Substr);
var stringObject = context.GetGlobalAs<CommonObject>("String");
stringObject.Prototype.Put("substr", substr);

private static CommonObject Substr(int startIndex, int length, CommonObject prototype)
{
    return prototype;
}
```

**Comment by fholm** [comment]
Follow these instructions for creating your own function: https://github.com/fholm/IronJS/wiki/Exposing-a-CLR-function-as-a-native-JavaScript-function

**Comment by asbjornu** [comment]
Thanks, I've now <a href="https://github.com/asbjornu/Uglify.NET/commit/ea501342f455e60f645bcbd5ddcdcbd6248819d5">implemented `String.prototype.substr`</a> and it seems to be working. The only quirk was that I needed to declare the method with `double` parameters instead of `int` since with `int`, IronJS threw the following exception:

```
IronJS.Error+CompileError : No conversion from Double to type Int32 exists
    at IronJS.Hosting.FSharp.run(Delegate compiled, T t) in Hosting.fs: line 152
```

**Comment by fholm** [comment]
Yeah, it's a known limitation (tm) that currently IronJS only accepts double numbers and does not conversions from/to other number types. It was just the fastest way to implement number handling in IronJS due to JavaScript only dealing with double floating point numbers. 

Conversions from/to the other number types are planned, ofc. and will come with the other missing .NET integrations.

**Comment by otac0n** [comment]
I added an implementation of `substr`.

**Comment by asbjornu** [comment]
Excellent, thanks for the great and almost instantaneous feedback!

**Comment by jdalton** [comment]
Just a note `String#substr`.
It's under the [Additional Properties](http://es5.github.com/#B.2) section of both ES3 and ES5 and as such

> Some implementations of ECMAScript have included additional properties for some of the standard native objects. This non-normative annex suggests uniform semantics for such properties **without making the properties or their semantics part of this standard**.

So technically it's not part of the standard. Which explains why JScript _(IE)_ has a different implementation of `String#substr` than others.
