### ISSUE TITLE
SL4.sln missing files

### ISSUE THREAD

**Issue by Meai** [fholm/IronJS#86]
Legacy.fs
SuffixString.fs

**Comment by otac0n** [comment]
Would you mind submitting a patch?

**Comment by Meai** [comment]
I'm sorry, I neither know git, nor this project. I just thought I should still mention this. I also don't know where these files are, there are some c# files with these names but adding those didn't solve the problem. In addition to that I don't know f#...

**Comment by otac0n** [comment]
Ok, I'll take a look.

**Comment by roubarbe** [comment]
parse error FS0225: Source file '/Users/username/IronJS/Src/IronJS/Legacy.fs' could not be found

parse error FS0225: Source file '/Users/username/IronJS/Src/IronJS/SuffixString.fs' could not be found

parse error FS0225: Source file '/Users/username/IronJS/Src/IronJS/SplayTree.fs' could not be found

parse error FS0225: Source file '/Users/username/IronJS/Src/IronJS/Caches.fs' could not be found

parse error FS0225: Source file '/Users/username/IronJS/Src/IronJS/ReflectionCache.fs' could not be found

While attempting to compile.

**Comment by fholm** [comment]
Wont fix this.
