### ISSUE TITLE
mono based linux build is broken

### ISSUE THREAD

**Issue by hewholived** [fholm/IronJS#99]
I tried compiling it on linux but the build script seems to be outdated. It would be super helpful of you if someone could get it fixed.

**Comment by gboya** [comment]
Current sources are incompatible with a build on Mono/Linux, beyond the build script in itself.
You have to make a few changes to make it build on Linux : 
- Ensure that all references to Fsharp.Core are properly configured, wrt your own installation of Fsharp. 
- On the IronJS and IronJS.Runtime project, in the build settings, define the LEGACY_BIGINT preprocessor directive.

You may then encounter the following compilation error.
- Under the IronJS.Runtime project, in the Objects/FunctionObjects.cs _Static Member cannot be accessed [...] with an instance reference._ → You need to replace `DynamicScope.Empty` by an explicit reference to the underlying type, ie `FSharpList<Tuple<int, IronJS.Runtime.CommonObject>>.Empty` 
- In the Error.cs file, you may encounter the error : _Accessor [...] must be declared public ..._ → Simply declare the CompilerError.Source setter public as a workaround.

Keep in mind however that all this is strongly dependent on your Mono version and your FSharp version/configuration. These workarounds worked for me, using Mono 3.0 on Ubuntu (installed from repos) and a version of F# directly built from the latest source of the official github repo (https://github.com/fsharp/fsharp) a few weeks ago.

**Comment by hewholived** [comment]
The above steps worked for me. Thanks!
